### ISSUE TITLE
Follow the Digital Lifecycle Program (DLP)

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#122] opened 2024-07-24 14:27 UTC
Follow GSA's [Digital Lifecycle Program](https://insite.gsa.gov/employee-resources/communications/websites/strategy-policy-and-standards/digital-lifecycle-program?term=DLP) for the website

Steps 2 and 3 are the most relevant.
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/tts.gsa.gov/issues/124
- [ ] https://github.com/GSA-TTS/tts.gsa.gov/issues/125
```

**Comment by debjudy** [comment] 2024-08-13 15:11
Duplicate of #124 and last task covered under #125

**Closed by debjudy** 2024-08-13 15:11 UTC
